<a href="https://colab.research.google.com/github/LamuneGitHub/A001_Python_Test/blob/main/python_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

arr_A = np.array( 
          [ [17,2]
         ,[136,33]]
)

arr_B = np.array( 
          [ 
              [3,13,14],
              [6,72,28],
              [9,2,42]
         ]
)

print( np.linalg.det(arr_B) )
print( np.linalg.inv(arr_B) )

-4.942712905631211e-13
[[-6.00479950e+15  1.04800746e+15  1.30292819e+15]
 [ 0.00000000e+00  1.41509434e-02 -9.43396226e-03]
 [ 1.28674275e+15 -2.24573027e+14 -2.79198899e+14]]


In [3]:
import numpy as np

x=[2, -1, 3, 2]
y=[3, 2, 1, -4]

print ( x, y )

arr_x = np.array(x)
arr_y = np.array(y)

# 내적
print ( (arr_x * arr_y).sum() )

[2, -1, 3, 2] [3, 2, 1, -4]
-1


# typing 라이브러리를 사용한 명시적 함수 정의 

In [4]:
# typing 라이브러리를 사용한 명시적 함수 정의 

from typing import List

# float 배열을 입력으로 받은 후 float 을 반환함을 명시 
def average( L: List[float] ) -> float:
	total_sum = 0
	for item in L :
		total_sum += item
	return total_sum / len(L)
 


input_value = [1.4 , 1.6 , 1.9 , 2.0 ]
print (average ( input_value )) 

'''
=> 1.725
'''

1.725


'\n=> 1.725\n'