<a href="https://colab.research.google.com/github/LamuneGitHub/A001_Python_Test/blob/main/python_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# S&P500 지수 조회 ( ^GSPC )
# 나스닥 지수 조회 ( ^IXIC )
# KOSPI 지수 조회 ( ^KS11 )

from pandas_datareader import data as pdr
import yfinance as yf
yf.pdr_override() 

p_start = '1987-01-01'
p_end = '2022-09-27'

# code_tmp = '^GSPC' 
# code_tmp = '^IXIC'
# code_tmp = '^KS11'

lst_code =  [ '^GSPC' , '^IXIC' , '^KS11' ]
for code_tmp in lst_code :
    # 주가조회 
    df_주가조회 = pdr.get_data_google( code_tmp , start=p_start , end=p_end )
    pdr.get_data_
    
    # 파일로 저장
    df_주가조회.to_csv( f'(세로)주가({code_tmp}){p_start})~({p_end}).csv') #, index=False)

AttributeError: module 'pandas_datareader.data' has no attribute 'get_data_google'

In [39]:
# 서부 텍사스 중질유(WTI Crude), monthly

start_date='1987-01-01'
end_date= '2022-09-27'

title = '서부텍사스중질유' # 국제 원유가격을 대표
code = 'POILWTIUSDM' 


df_tmp = pdr.get_data_fred(code,  start=start_date )
# 파일로 저장
df_tmp.to_csv( f'{title}({p_start})~({p_end}).csv') #, index=False)

print('row count:', len(df_tmp))
df_tmp.tail(5) # 2달 전 데이터

row count: 391


POILWTIUSDM
DATE                   
2022-03-01   109.852609
2022-04-01   102.781429
2022-05-01   110.650455
2022-06-01   115.649091
2022-07-01   103.734762

In [38]:
# 두바이유(dubai crude )), monthly

start_date='1987-01-01'
end_date= '2022-09-27'

title = '두바이유' # 국내에서 주로 수입
code = 'POILDUBUSDM' 


df_tmp = pdr.get_data_fred(code,  start=start_date )

# 파일로 저장
df_tmp.to_csv( f'{title}({p_start})~({p_end}).csv') #, index=False)


print('row count:', len(df_tmp))
df_tmp.tail(5) # 2달 전 데이터

row count: 391


POILDUBUSDM
DATE                   
2022-03-01   107.587826
2022-04-01   102.755238
2022-05-01   107.861364
2022-06-01   111.859545
2022-07-01   100.318571

In [36]:
# 금가격 조회

start_date='1987-01-01'
end_date= '2022-09-27'

title = '금'
code = 'LBMA/GOLD'

import quandl
import pandas as pd

quandl_key = '3666KszMm_esaQCBhm5T'
quandl.ApiConfig.api_key = quandl_key

df_tmp = quandl.get(dataset=code, start_date=start_date, end_date= end_date)

df_tmp2 = df_tmp[['USD (PM)']]
# 파일로 저장
df_tmp2.to_csv( f'{title}({p_start})~({p_end}).csv') #, index=False)

df_tmp2.tail()


USD (PM)
Date                
2022-09-20   1664.15
2022-09-21   1671.75
2022-09-22   1671.85
2022-09-23   1643.55
2022-09-26   1643.35

In [33]:
# 구리 가격 조회

start_date='1987-01-01'
end_date= '2022-09-27'

title = '구리'
code = 'ODA/PCOPP_USD'


import quandl
import pandas as pd

quandl_key = '3666KszMm_esaQCBhm5T'
quandl.ApiConfig.api_key = quandl_key

df_tmp = quandl.get(dataset=code, start_date=start_date, end_date= end_date)
# 파일로 저장
df_tmp.to_csv( f'{title}({p_start})~({p_end}).csv') #, index=False)

df_tmp2.tail()

USD (AM)  USD (PM)
Date                          
2022-09-20   1667.90   1664.15
2022-09-21   1674.45   1671.75
2022-09-22   1671.85   1671.85
2022-09-23   1661.45   1643.55
2022-09-26   1647.00   1643.35

----

In [4]:
primes = [2, 3, 5, 7, 11, 13]

def product(*numbers):
    print ( numbers)

product (*primes )

product (primes )


(2, 3, 5, 7, 11, 13)
([2, 3, 5, 7, 11, 13],)


TypeError: __main__.product() argument after ** must be a mapping, not list

In [4]:
tmp = '12,578'

#int(tmp.replace(tmp[2], ''))


a, b = tmp.split(",")
int(a+b)

12578

In [5]:
int(str(tmp))

ValueError: invalid literal for int() with base 10: '12,578'

In [ ]:
def trueIndex리스트반환 ( condition ) :

    list_True = []
    for idx , x in enumerate(condition) :
        if x :
            list_True.append( idx )
    #print ( f"찾은 idx {list_True}" )

    return list_True

----
----


In [2]:
import numpy as np

arr_A = np.array( 
          [ [17,2]
         ,[136,33]]
)

arr_B = np.array( 
          [ 
              [3,13,14],
              [6,72,28],
              [9,2,42]
         ]
)

print( np.linalg.det(arr_B) )
print( np.linalg.inv(arr_B) )

-4.942712905631211e-13
[[-6.00479950e+15  1.04800746e+15  1.30292819e+15]
 [ 0.00000000e+00  1.41509434e-02 -9.43396226e-03]
 [ 1.28674275e+15 -2.24573027e+14 -2.79198899e+14]]


In [3]:
import numpy as np

x=[2, -1, 3, 2]
y=[3, 2, 1, -4]

print ( x, y )

arr_x = np.array(x)
arr_y = np.array(y)

# 내적
print ( (arr_x * arr_y).sum() )

[2, -1, 3, 2] [3, 2, 1, -4]
-1


# typing 라이브러리를 사용한 명시적 함수 정의 

In [4]:
# typing 라이브러리를 사용한 명시적 함수 정의 

from typing import List

# float 배열을 입력으로 받은 후 float 을 반환함을 명시 
def average( L: List[float] ) -> float:
	total_sum = 0
	for item in L :
		total_sum += item
	return total_sum / len(L)
 


input_value = [1.4 , 1.6 , 1.9 , 2.0 ]
print (average ( input_value )) 

'''
=> 1.725
'''

1.725


'\n=> 1.725\n'