<a href="https://colab.research.google.com/github/LamuneGitHub/A001_Python_Test/blob/main/n131%20-%20Linear%20Algebra/n131a%20-%20Linear%20Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src='https://i.imgur.com/RDAD11M.png' width = '200' align = 'right'>

## *DATA SCIENCE / SECTION 1 / SPRINT 3 / NOTE 1*

# 📝 Assignment

# 🌱 **기본 과제**

## **Part 1. Dot product & Matrix Multiplication**

### **1-1. Dot product**

- Dot product를 이용하여 구매자별 구매 총합을 계산하세요.
  - Data Description
    - People : 구매자
    - Name : 제품명
    - Price : 제품 개당 가격
    - Amount : 제품 구매 갯수

|People|Name|Price|Amount|
|:-:|:-:|:-:|:-:|
|X|A|100|35|
|X|B|500|10|
|X|C|250|25|
|X|D|50|40|
|Y|A|100|-|
|Y|B|500|50|
|Y|C|250|50|
|Y|D|50|-|
|Z|A|100|-|
|Z|B|500|-|
|Z|C|250|100|
|Z|D|50|-|

##### **Q1. Dot product를 통해 구한 구매자 X의 구매 총합을 쓰세요.**

In [4]:
import numpy as np

price = np.array([100, 500, 250, 50])
X = np.array([35, 10, 25, 40])
Y = np.array([0, 50, 50, 0])
Z = np.array([0, 0, 100, 0])

res1 = [np.dot(price, person) for person in (X, Y, Z)]
res1

[16750, 37500, 25000]

### **1-2. Matrix Multiplication**
- Matrix Multiplication을 이용하여 구매자별 구매 총합을 계산하세요.

##### **Q2. Matrix Multiplication을 통해 구한 구매자 Y의 구매 총합을 쓰세요.**

In [5]:
amount = np.array([[35, 10, 25, 40], [0, 50, 50, 0], [0, 0 , 100, 0]])
price = np.array([100, 500, 250, 50])

res2 = np.matmul(amount, price)
res2[1]

37500

## **Part 2. Numpy 연산**

### **2-1. Norm**

- 주어진 값 $x_0, x_1, ... x_n$ 를 element로 갖는 $\vec v$에 대하여 
  - $L_1$ Norm 의 정의는 다음과 같습니다. 
    > $|\vec v| = |x_0| + |x_1| + ... + |x_n|$ <br>
  - $L_2$ Norm 의 정의는 다음과 같습니다.
    > $||\vec v|| = \sqrt {{x_0}^2 + {x_1}^2 + ... + {x_n}^2}$
- 이를 참조하여 주어진 벡터에 대해서 $L_2$ Norm 의 값과 $L_1$ Norm 의 값의 차의 절대값을 계산하는 함수를 만드세요.

##### **Q3. $\vec v = [3, -1, 8, 9]$일 때, NormDif($\vec v$)의 결과값을 반올림하여 소수점 둘째 자리까지 쓰세요.**

In [6]:
def NormDif(v):
  L1_Norm = 0 
  for x in v :
    L1_Norm += abs(x)
  
  L2_Norm = 0
  for x in v :
    L2_Norm += x**2
  L2_Norm = L2_Norm ** (1/2)

  return abs( L1_Norm - L2_Norm )
    

In [12]:
v1 = np.array( [ 3, -1 , 8 , 9 ] )
round( NormDif(v1) , 2 )

8.55

### **2-2. Errors**

- 2개의 벡터와 error의 타입을 입력받아 그 결과값을 계산하는 함수를 작성하세요.
  - error의 타입은 `MSE`, `MAE` 2가지입니다.
> ${\rm MSE} = {1 \over n} \sum_{i=1}^n ({\hat Y_i}-Y_i)^2$
>
> ${\rm MAE} = {1 \over n} \sum_{i=1}^n |{\hat Y_i}-Y_i|$
>
> where $\hat Y_i$ : 예측값(prediction), $Y_i$ : 실제값(target) 

##### **Q4. 예측값 $x = [2085, 1815, 2235, 1400, 2500, 1430, 3070, 2000, 1299, 1180]$ 이고, 실제값 $y=[2103, 2099, 1985, 1630, 2480, 1300, 3200, 1990, 1405, 1210]$ 일 때, error 함수를 통해 얻은 MSE와 MAE 결과값을 (MSE 값, MAE 값) 형태로 쓰세요.**

In [13]:
def error(x, y, type):
  ret_value = 0

  if type == 'MSE' :
    for i in range(len(x)) :
      ret_value += (x[i] - y[i])**2
    ret_value = ret_value / len(x)

  else :
    for i in range(len(x)) :
      ret_value += abs((x[i] - y[i]))
    ret_value = ret_value / len(x)

  return ret_value


In [14]:
𝑥=np.array ([2085,1815,2235,1400,2500,1430,3070,2000,1299,1180])  
𝑦=np.array ([2103,2099,1985,1630,2480,1300,3200,1990,1405,1210])

print ( error(x,y,"MSE") , error(x,y,"MAE") )


24281.6 120.8


## **Part 3. Span**

- 다음 벡터들의 span과 이것이 의미하는 바를 설명하세요.
> $g = \begin{bmatrix} 1 & 3 \end{bmatrix}
\qquad
h = \begin{bmatrix} 2 & 6 \end{bmatrix}$

  - `np.stack()`을 사용하여 두 벡터 g, h를 하나의 matrix로 합치세요.
  - matrix의 rank를 구해 보세요. 

In [17]:
𝑔=np.array([1,3])
ℎ=np.array([2,6])

m = np.stack((g,h))


np.linalg.matrix_rank(m)

1

##### **Q5. 두 벡터 g와 h의 span으로 옳은 것을 고르세요.**
- 점 
- 직선
- 평면 
- 3차원 공간 



##### **Q6. rank를 통해 확인할 수 있는 두 벡터 g와 h의 관계로 옳은 것을 고르세요.**
- 선형 관계에 있는 벡터(Linearly dependent vector)
- 선형 관계가 없는 벡터(Linearly independent vector) 

In [18]:

np.linalg.matrix_rank(m)

1

# 🥇 **도전 과제** 

## **Part 4. Cramer's rule**

- **Cramer's rule을 사용해 $x_1$, $x_2$, $x_3$의 값을 구하세요. (단, 반올림하여 소수점 둘째 자리까지 쓰세요.)**
> $x_1$ + $2x_3$ = 6
>
> $-3x_1$ + $4x_2$ + $6x_3$ = 30
>
> $-x_1$ $-2x_2$ + $3x_3$ = 8

In [46]:
A = np.array (
              [  [ 1 , 0 , 2 ], 
                [-3 , 4 , 6 ],
                [-1 , -2 , 3 ]
              ]
              )

B = np.array (  [ 6 , 30 , 8 ] )

X = np.linalg.solve(A, B)
print( X )

print( np.round(X,2) )

print( X.round(2) )


[-0.90909091  1.63636364  3.45454545]
[-0.91  1.64  3.45]
[-0.91  1.64  3.45]
